MoviesProjectMini/MoviesProjectMini/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MoviesProjectMini.Models;

namespace MoviesProjectMini.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IStoreRespository repository;

        public NavigationMenuViewComponent(IStoreRespository repo)
        {
            repository = repo;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(repository.Movies
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

MoviesProjectMini/MoviesProjectMini/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MoviesProjectMini</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="/resetCss/reset.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    @*<link href="/" rel="stylesheet" />*@
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Redressed&display=swap" rel="stylesheet">

</head>
<body>
    <div class="bg-dark text-white p-2">
        <div class="navbar-brand ml-2 text-uppercase">
            <partial name="./components/header" />
        </div>
    </div>
    <div class="row m-1 p-1">
        <div class="pb-3 row col-12">
            <div class="col-3">
                <vc:navigation-menu />
            </div>
            <div class="col-9">@RenderBody()</div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MoviesProjectMini - <a asp-area="" asp-controller="Home" asp-action="Privacy">Ducnhudaik</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>